proxmox_node_hostname: enterprise

# KEYS FOR TEMPLATE HOSTS
#
# required
# hostname: "{{ item.name }}"
# vmid: "{{ item.vmid }}"
# vztmpl_filename: "{{ item.vztmpl_filename }}"
# ostype: "{{ item.ostype }}"
#
# calculated
# container_name: "{{ item.name | replace('_', '-') }}"
# template_host_record: "{{ host_addresses | ansible.builtin.json_query(hostname) }}"
# mac_address: "{{ template_host_record.mac }}"
# ip_address: "{{ template_host_record.ip }}"
#
# optional
# cores: "{{ item.cores | default(2) }}"
# disk_size: "{{ item.disk_size | default(20) }}" # in GiB
# memory: "{{ item.memory | default(2148) }}" # in MB
# start_on_boot: "{{ item.start_on_boot | default(true) }}"
# swap: "{{ item.swap | default(512) }}"

template_hosts:
  - {
      name: "debian12_template",
      vmid: 999,
      vztmpl_filename: "{{ proxmox_debian_12_vztmpl_filename }}",
      ostype: "debian",
    }

# KEYS FOR CLONE HOSTS
#
# required
# name: "centaurus"
# clone_vmid: 999
#
# calculated
# container_name: "{{ item.name | replace('_', '-') }}"
# clone_host_record: "{{ host_addresses | ansible.builtin.json_query(hostname) }}"
# mac_address: "{{ clone_host_record.mac }}"
# ip_address: "{{ clone_host_record.ip }}"

container_clone_hosts:
  - { name: "centaurus", clone_vmid: 999 }
