proxmox_api_port: 8006
proxmox_root_api_user: root@pam
proxmox_admin_api_user: "{{ proxmox_admin_username + '@' + proxmox_admin_authentication_realm }}"
proxmox_admin_firstname: Kate
proxmox_vm_ct_iso_vztmpl_storage: local
proxmox_vm_ct_disk_storage: local-lvm
proxmox_debian_12_vztmpl_filename: debian-12-standard_12.12-1_amd64.tar.zst
proxmox_node_ip: "{{ ansible_host }}"
proxmox_ansible_public_key: "{{ ansible_public_key }}"
proxmox_gateway: "{{ trusted_gateway }}"
