proxmox_api_port: 8006
proxmox_root_api_user: root@pam
proxmox_admin_api_user: "{{ proxmox_admin_username + '@' + proxmox_admin_authentication_realm }}"
proxmox_admin_firstname: Kate
proxmox_vm_ct_iso_vztmpl_storage: local
proxmox_vm_ct_disk_storage: local-lvm
proxmox_debian_13_vztmpl_url: "http://download.proxmox.com/images/system/debian-13-standard_13.1-2_amd64.tar.zst"
proxmox_debian_13_vztmpl_filename: "{{ (proxmox_debian_13_vztmpl_url | split('/'))[-1] }}"
proxmox_ansible_host: "{{ ansible_host }}"
proxmox_ansible_public_key: "{{ ansible_public_key }}"
